apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-scale
  namespace: demo
spec:
  scaleTargetRef:
   kind: Deployment
   name: main-nginx-ingress-controller
  minReplicaCount: 1
  maxReplicaCount: 20
  cooldownPeriod: 30
  pollingInterval: 1
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-server.demo
      metricName: nginx_connections_active_keda
      query: |
        sum(avg_over_time(nginx_ingress_nginx_connections_active[1m]))
      threshold: "100"