apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    project: {{ .Release.Name }}
  ports:
    - port: 8080
      targetPort: {{ .Values.container.port }}
      protocol  : TCP
  type: LoadBalancer