apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app : {{ .Release.Name }}
spec:
  ports:
    - port: 8080
      targetPort: {{ .Values.container.port }}
      protocol  : TCP
  replicas: {{ .Values.replicaCount }}
  selector:
    app: {{ .Release.Name }}
    matchLabels:
      project: {{ .Release.Name }}
  type: LoadBalancer