apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: keda-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-service
  namespace: demo
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: web
        image: cplk01/messanger-web:latest
        # Need to use secrets or config map later
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: demo
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: test
  type: ClusterIP