apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: rate-limit-policy
  namespace: demo
spec:
  rateLimit:
    rate: 10r/s
    key: ${binary_remote_addr}
    zoneSize: 10M
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: demo-vs
  namespace: demo
spec:
  ingressClassName: nginx
  host: "example.com"
  policies:
  - name: rate-limit-policy
  upstreams:
  - name: test
    service: test
    port: 8080
  - name: api
    service: api
    port: 3000

  routes:
  - path: /test
    action:
      pass: test
  - path: /api
    action:
      pass: api